services:
   web:
    build: .
    command:  >
      sh -c "python manage.py migrate --settings=vercel_app.dev && 
             python manage.py runserver 0.0.0.0:8000 --settings=vercel_app.dev"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my_network

   db:
    image: postgres:13.15-bullseye
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - my_network
  
networks:
  my_network:
    driver: bridge